### PR TITLE
fix: remove 100mb limit from uploader

### PR DESCRIPTION
**Pull request by alanshaw**
This PR changes the uploader to always pack the file into a CAR so the upload limit is removed.

### CODE REVIEW

**Review by vasco-santos — APPROVED** [review]
LGTM! 
Sad that File does not allow us to get the total size, otherwise we could add to the uploaded info the total size, but also the user can see it locally

**Comment by alanshaw** [comment]
> LGTM!
> Sad that File does not allow us to get the total size, otherwise we could add to the uploaded info the total size, but also the user can see it locally

We could use the `size` property no? https://developer.mozilla.org/en-US/docs/Web/API/File/size

What would we show - percentage complete?

**Comment by vasco-santos** [comment]
> We could use the size property no? https://developer.mozilla.org/en-US/docs/Web/API/File/size

Oh, I looked at https://github.com/web-std/file/blob/default/src/lib.js and did not see size in there. But if we have in the browser, yes let's to it

> What would we show - percentage complete?

I think that is more user friendly than x mb / y mb, so yes percentage ❤️

**Review by vasco-santos — APPROVED** [review]
LGTM 💯

**Pull request merged**
